config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :comments
  resources :users

  post '/comments/:id', to:'comments#tag'

  get    '/signup',   to: 'users#new'
  post   '/signup',   to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get    '/tutorial',   to: 'welcome#tutorial'

  get    '/stats',   to: 'stats#index'
  get    '/stats/all',   to: 'stats#all'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/function.rb
class Function < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
   has_secure_password
   validates :email, presence:   true, length: { maximum: 255 },
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  include CommentsHelper
  include UsersHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_user, only: [:show, :tag]
  before_action :set_comment, only: [:show, :tag]
  

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    if(params[:id].to_i > @user.current_comment_id)
      redirect_to Comment.find(@user.current_comment_id)
    end
    @tag = Tag.where(user_id: session[:user_id], comment_id: @comment.id).first
  end

   # GET /comments/new
  def new
    @comment = Comment.new
  end

  # POST /comments
  # POST /comments.json
  #NOTE- Not used in this implementation.
  def create
    # @comment = Comment.new(comment_params)

    # respond_to do |format|
    #   if @comment.save
    #     format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
    #     format.json { render :show, status: :created, location: @comment }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @comment.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # POST /comments/id
  def tag
    #Create or update tag
    @tag = Tag.where(user_id: session[:user_id], comment_id: @comment.id).first
    if @tag.nil?
      @tag = Tag.new do |t|
        t.user_id = session[:user_id]
        t.comment_id = @comment.id
        t.body = params[:tag]
        t.split = params[:split] ? true : false
      end
    else
      @tag.body = params[:tag]
      @tag.split = params[:split] ? true : false
    end

    #Save tag 
    if @tag.save
      @user.increment!(:current_comment_id) if (@user.current_comment_id == params[:id].to_i)
      redirect_to next_comment, notice: "Your tag has been saved!"
    else
      redirect_to @comment, alert: 'Something went wrong!'
    end
  end



  private

    # set user variable using session parameters
    def set_user
      if !session[:user_id]
        redirect_to root_path
      else 
        @user = User.find_by(id: session[:user_id])
        if @user.nil?
          log_out
          redirect_to root_path
        end
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      comment_id = translate_index(params[:id])
      @comment = Comment.find(comment_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.fetch(:comment, {})
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # GET /login
  def new
    if session[:user_id]
        @user = current_user
        redirect_to current_comment
    end
  end

  #POST /login
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      redirect_to current_comment, notice: "You have been logged in successfully!"
    else
      flash.now[:alert] = 'Invalid email/password combination'
      render 'new'
    end
  end

  # DELETE /logout
  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  def index
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  # GET /users
  # GET /users.json
  # NOTE currently unimplemented
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  # NOTE currently unimplemented
  def show
  end

  # GET /signup
  def new
    @user = current_user
    if @user 
        redirect_to current_comment
    end
  end

  # POST /signup
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        @user.update(current_comment_id: 1)
        format.html { log_in @user
          redirect_to tutorial_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { flash.now[:alert] = 'Ensure that both passwords match and are at least 6 characters long.'
          render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = current_user
    if @user 
      redirect_to current_comment
    end
  end
  def tutorial
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def current_comment
    return Comment.find(@user.current_comment_id) unless @user.current_comment_id > Comment.count
    return Comment.find(@user.current_comment_id-1)
  end

  def prev_comment
    if params[:id].to_i > 1
      return Comment.find(params[:id].to_i - 1)
    else
      return Comment.find(params[:id].to_i)
    end
  end

  def next_comment
    if params[:id].to_i < Comment.count
      return Comment.find(params[:id].to_i+ 1)
    else
      return Comment.find(params[:id].to_i)
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user
    return User.find_by(id: session[:user_id])
  end

  def translate_index(comment_index)
    items = [*1..Comment.count]
    items.shuffle!(random: Random.new(session[:user_id]))
    return items[comment_index.to_i - 1]
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.haml
= form_for @comment do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      %ul
        - @comment.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', comments_path

app/views/comments/index.html.haml
%h1 Listing comments

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @comments.each do |comment|
      %tr
        %td= link_to 'Show', comment
        %td= link_to 'Edit', edit_comment_path(comment)
        %td= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }
%br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.haml
#content
    %br
    #navigation
        .left{:style => "float:left"}
            -if params[:id].to_i > 1
                = link_to 'Prev', prev_comment
            -else
                Prev
            \|
            -if params[:id].to_i != @user.current_comment_id and params[:id].to_i != Comment.count
                = link_to 'Next', next_comment
            -else
                Next
        .right{:style => "float:right"}
            = link_to "Log out", logout_url, method: :delete
        .center{:style => "text-align: center; width:30%; margin:auto;"}
            / Comment #{@project_number}/#{Comment.all.count}
            Comment #{params[:id]}/#{Comment.count} (##{@comment.id})
    %br
    %hr
    -if @user.current_comment_id.to_i == Comment.all.count+1
        %h2{:style => "text-align: center; font-size: 2.7em; line-height: 1.5em;"} You have successfully completed tagging all of the comments! Thank you for your contribution.
        %hr
    #instructions
        Spend a moment reading through the function and the comment. Then, highlight the 0-12 words in the comment that most usefully describe the function's purpose . If you believe there is more useful information than one tag can hold, choose the most appropriate tag and check the "Multiple Tags?" box. Once you have finished, click submit or press enter to continue.
        =link_to "View Demo", tutorial_url
    %hr
    %table#main_content
        %tr
            %td.content_item
                %h2{:style => "line-height:0em;"} Function
                %p (Found in the file #{@comment.file_name})
                #function=  @comment.function_body.gsub('\n', "\n")
                    
            %td.content_item
                %h2 Comment
                #comment=  "&#8203;".html_safe + @comment.body.gsub('\n', "\n").gsub('\t', '').gsub('*', "")[2..-3].squeeze(" ")
                %br
                You have selected:
                #confirmation= @tag.body if @tag
                = form_tag 
                = hidden_field_tag :tag
                .left{:style => "float:left"}
                    =label_tag "split", "Multiple Tags?" do
                        =check_box_tag "split", true, (@tag.split if @tag)
                        Multiple Tags?
                .right{:style => "float:right; display: block;"}
                    = submit_tag "Submit", :id => "submit"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FunCom
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - flash.each do |key, value|
      - unless flash[key].blank?
        %p{ :class => "flash #{key}" }= value
    = yield

app/views/stats/index.html.haml
-Comment.all.each do |comment|
  %p
    id 
    =comment.function_id
  %p
    body 
    =comment.body
  -Tag.where(comment_id: comment.id).each do |tag|
    %p
      user
      =tag.user_id
      =tag.body
  %br

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.email
        %td= link_to 'Show', user

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
=link_to "Back", root_path
%br
= form_for :user, :url => signup_path do |f|
	= f.label :email
	= f.text_field :email
	= f.label :password
	= f.password_field :password
	= f.label :password_confirmation, "Confirm Password"
	= f.password_field :password_confirmation
	= submit_tag "Submit"

app/views/users/show.html.haml
%p#notice= notice

-Tag.all.where(user_id: @user.id).each_with_index do |tag, index|
	=index
	%br
	=tag.body
	%br
	=Comment.all.find(tag.comment_id).body
	%br
	%br

\|
= link_to 'Back', users_path

app/views/welcome/index.html.haml
%h1 Comment Tagging Project
%br
#informed_consent{:style => "height:50%; overflow:scroll; outline: solid thin; padding: 20px;"}
    %h2 Informed Consent Form
    %h3 Purpose of the Study:
    %p This is a study in computer science conducted by Zachary Eberhart, PhD student in the University of Notre Dame. The purpose of this study is to tag the most concise, useful sections of comments for a set of functions found in open-source Debian projects.

    %h3 What will be done:
    %p You will:
    %ol
        %li Create an account on our web interface.
        %li Examine the source code, file name, and comment of a particular function.
        %li Using only the provided project information, you will tag 0-12 contiguous word in the comment that most concisely describe the function's utility (i.e. WHAT the function does, not HOW or WHY it does it).
        %li Repeat until the previously agreed-upon time/tag quota has been met.
        
    %p After you save your responses, we will analyze the data, and find common patterns in the data.

    %h3 Benefits of this Study:
    %p You will be contributing to knowledge of software engineering. In addition, you will be compensated for your time at a previously agreed-upon rate.

    %h3 Risks or discomforts:
    %p No risks or discomforts are anticipated from taking part in this study. If you are unable to comlete the study in one sitting, you may exit the session and login at a later time using your submitted account information. If you feel uncomfortable about this study, you can withdraw from the study. 

    %h3 Confidentiality:
    %p Your results and identity will be kept completely confidential. We will ask you to register using an email address so that you can login to complete the study should you log out. The password you provide will be encrypted. We may communicate with you at the provided email address to coordinate study and payment information. Once the study has been completed, your contact information will be purged from our database. Your contact information will be given to no 3rd parties.

    %h3 Decision to quit at any time:
    %p Your participation is voluntary; you are free to withdraw your participation from this study at any time. If you do not want to continue, you can simply exit the web interface. 

    %h3 How the findings will be used:
    %p The results of the study will be used for scholarly purposes only. The results from the study will be presented in educational settings and at professional conferences, and the results might be published in a professional journal in the field of computer science.

    %h3 Contact information:
    %p If you have concerns or questions about this study, please contact 
    %p Researcher: Zachary Eberhart at zeberhar@nd.edu.
    %p Institutional Review Board: http://or.nd.edu/research-compliance/human-subjects-research/institutional-review-board-irb/
    %p Office of Research Compliance: compliance@nd.edu or call (574) 631-1389
%br 
%p By clicking "Sign Up" or "Login," you acknowledge that you have read this information and agree to participate in this research, with the knowledge that you are free to withdraw your participation at any time without penalty, that you understand the study described above, and that you are 18 years of age or older. 
%br
= link_to "Sign up", signup_url
\|
= link_to "Login", login_url
%br

app/views/welcome/tutorial.html.haml
%br
#tutorial{:style => "width:95%; display: block; margin: auto;"}
    %h1 Comment Tagging Project - Tutorial
    %h2 Please read through before beginning. You may return to this page at any time.
    %hr
    %br
    #stuff{:style => "box-sizing: border-box; width:100%; background-color: white !important; padding:10px 10%; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.15), 0 6px 20px 0 rgba(0, 0, 0, 0.19); border-radius: 5px;"}
        %h2 Introduction
        %p Welcome to our comment tagging project! The purpose of this study is to extract the most relevant pieces of information from comments describing a diverse set of functions. All of these functions come from open-source Debian projects, and are written in C or C++. The comments associated with each function often provide a plethora of information about the functionality of the methods. Oftentimes, however, they contain more information than is necessary to gain a general, high-level understanding of the code.

        %p In this study, we would like you to read through each comment and tag the short phrase that summarizes <em>what</em> the function does or <em>what</em> it is, as opposed to when, where, how, or why it is used. We have provided an interface that should make it simple to do just that. When you click "Return to Tagging Page", you should come to a page that looks like this:

        %br
        = image_tag  "screenshot.png", style: 'width:75%;  display: block; margin: auto;'
        %br

        %p On the right is the comment of interest, and on the left is the source code of function being described. To tag the relevant section of the comment, you simply highlight the desired comment text with your mouse. Try it below:

        #commentW &#8203; Add the sign into the signlist. Find the right spot to do it though.
        %br
        #confirmationW

        %p 
            In this case, you would want to tag the phrase 
            %span.confirmation "Add the sign into the signlist." 
            as that is the section that succinctly describes <em>what</em> the function does. "Find the right spot to do it though." is a suggestion to the programmer of where to use it.

        %p You will notice that the selection snaps to include only full words. Additionally, if the selection is longer that 12 words, it will narrow it down to include only the first 12. In some cases, you will find that <em>no part</em> of the comment contains information relevant to what the function does. In this case, simply don't tag anything. If you accidentally highlight something, you can click elsewhere in the comment box to untag it. 

        %p In other cases, you will find that more than 12 contiguous words are needed to fully describe what the method does. In those cases, you may choose the best 12 words to tag, and then mark the "Multiple Tags?" checkbox.

        =label_tag "split", "Multiple Tags?" do
            =check_box_tag "split", true, (@tag.split if @tag)
            Multiple Tags?

        %br

        %p Once you have tagged the comment in this manner, you can either hit the "Submit" button or press Enter on your keyboard to save your tag and continue to the next page. 

        %br

        %h2 Examples
        %table.examples
            %tr
                %td
                    .comment 
                        &#8203; Tries to pop a value off the queue  Returns 1 if successful, &#8203;
                %td 
                    %p
                        The phrase you would tag here is 
                        %span.confirmation "Tries to pop a value off the queue".
                        The fact that the functions returns 1 is irrelevant to the high-level functionality.
            %tr
                %td
                    .comment 
                        &#8203; If it has not already been allocated, allocate the UnpackedRecord   structure &#8203;
                %td 
                    %p  
                        Even though the function only operates if some condition is met, the purpose of the function is to 
                        %span.confirmation "allocate the UnpackedRecord structure",
                        so we would tag that.

            %tr
                %td
                    .comment
                        &#8203;\brief Release fritzbox connection  
                        \param nSock socket handle  
                        \param nApplId registered application id
                        \return error code (CapiNoError or CapiRegNotInstalled on error) &#8203;
                %td 
                    %p 
                        The tag here is 
                        %span.confirmation "Release fritzbox connection".
                        The rest consists of implementation details.
            %tr
                %td
                    .comment 
                        &#8203;​ Clear all authentication information. &#8203;
                %td 
                    %p
                        In this case, the comment is already very concise, and the entire phrase consists of information relevant to the functionality, so you would tag the entire thing: 
                        %span.confirmation "Clear all authentication information."
            %tr
                %td
                    .comment 
                        &#8203;​ Create and start asynchronous DNS query for a single resource. &#8203;
                %td 
                    %p
                        Again, the entire phrase is relevant and less than 12 words. If it were longer, you could leave off trailing phrases such as "for a single resource," but in this case you can tag the whole thing: 
                        %span.confirmation "Create and start asynchronous DNS query for a single resource."
            %tr
                %td
                    .comment 
                        &#8203;  Same as file_isfile(), but takes into account symlinks. &#8203;
                %td 
                    %p
                        This comment references another function, but gives no information as to the functionality of the function it is supposed to be describing. In this case, you would not tag anything and simply hit the submit button.
            %tr
                %td
                    .comment 
                        &#8203; @return 1=replaced , 2=not replaced , <=0 = error &#8203;
                %td 
                    %p
                        Although this comment describes what the function returns, it does not describe what the function does. Clearly it has something to do with replacements, but no phrase in the comment makes it clear. Therefore, you would tag nothing.
            %tr
                %td
                    .comment 
                        &#8203;  Return possible_type struct for current segment type. &#8203;
                %td 
                    %p
                        Like the previous example, this comment describes the return value. Unlike that example, this one also includes functionality information. It seems the purpose of this function is to construct and return a new item based on the current "segment type." You may want to read the function here to confirm, and if so, you would tag the entire phrase: 
                        %span.confirmation "Return possible_type struct for current segment type."
            %tr
                %td
                    .comment 
                        &#8203;Willy Robison's contribution  HTM1735 from Humirel (www.humirel.com) hooked up like 
                        everyone  else. The datasheet seems to suggest that the humidity  measurement isn't too 
                        sensitive to VCC (VCC=5.0V +/- 0.25V).  The conversion formula is derived directly from the 
                        datasheet  (page 2). VAD is assumed to be volts and H is relative  humidity in percent. 
                        &#8203;
                %td 
                    %p 
                        Allthough this comment is quite long and detailed, it does not describe any functionality. Therefore, you would not tag anything.

            %tr
                %td
                    .comment 
                        &#8203;\property QTableView::cornerButtonEnabled
                        \\brief whether the button in the top-left corner is enabled

                        If this property is true then button in the top-left corner
                        of the table view is enabled. Clicking on this button will
                        select all the cells in the table view.

                        This property is true by default.​  \pro &#8203;
                %td 
                    %p 
                        Although it might be tempting to go with the brief "whether the button in the top-left corner is enabled" or the verb phrase "select all the cells in the table view", that is not what this function does – by reading the source code, you can tell that this function is responsible for enabling the button that selects those cells. The most apt tag in this comment is then
                        %span.confirmation "button in the top-left corner of the table view is enabled"
            %tr
                %td
                    .comment 
                        ​Internal function: _al_event_queue_push_event
                        Event sources call this function when they have something to add to
                        the queue. If a queue cannot accept the event, the event's
                        refcount will not be incremented.
                         
                        If no event queues can accept the event, the event should be
                        returned to the event source's list of recyclable events.​Intern
                        
                %td 
                    %p 
                        This is a very descriptive comment that communicates many of the details of the funciton, but as always, we are only concerned with the very basic information: WHAT does the function do? From this high-level, this comment is essentially just a push, and you would tag
                        %span.confirmation "add to the queue".
            %tr
                %td
                    .comment 
                        &#8203;See "An O(ND) Difference Algorithm and its Variations", by Eugene Myers.  Basically considers a "box" (off1, off2, lim1, lim2) and scan from both  the forward diagonal starting from (off1, off2) and the backward diagonal  starting from (lim1, lim2). If the K values on the same diagonal crosses  returns the furthest point of reach. We might end up having to expensive  cases using this algorithm is full, so a little bit of heuristic is needed  to cut the search and to return a suboptimal point.
                        &#8203;
                %td 
                    %p 
                        There is a lot going on in this comment, and it might take more than one short tag to adequately describe it. We 
                        %span.confirmation 'consider a "box",'
                        %span.confirmation 'scan from both the forward diagonal[...] and the backward diagonal,' 
                        and 
                        %span.confirmation 'return the furthest point of the reach.' 
                        None of those phrases quite describe the functionality on their own, but together they give a decent idea of the function's purpose. Therefore, you would likely choose to tag one of them and check the "Multiple Tags?" box.


        %h2 Conclusion
        %p As you can see, it is often very simple to glance at a comment and discern which part is relevant, if any part is at all! In some cases, if the comment is long or confusing, it will be helpful to skim through the function and try to determine broadly what it is doing. You don't need to be familiar with any of the specific details of the projects, just able to determine what is important.

        %p <b>Don't get stuck on any one comment for too long!</b> If you feel that you can't make heads or tails of a function, simply highlight whatever makes the most sense and move on. Just do your best! If you ever realize you make a mistake, you can always go back to a previous page.

        %p These tags will be used by software engineering researchers to better understand the role of documentation in computer science. Thank you very much for participating in this important study!

        %h2{:style => "text-align:center; color: #a360d3;"}=link_to "Return to Tagging Page", Comment.find(@user.current_comment_id)
        %br
        %br
    %br
    %br
    %br